### ISSUE TITLE
Ispravke za imena

### ISSUE THREAD

**Issue by Thalvik** [Shonetow/Imena-po-padezima#1]
Super ideja. Trenutno ime Aleksandar vraća na primer u genitivu "Imate zahtev za prijateljstvo od Aleksandara.", a ispravno bi bilo "Imate zahtev za prijateljstvo od Aleksandra." :)

**Comment by turshija** [comment]
Upravo sam hteo da otvorim isti issue :) Svaka cast za biblioteku !

**Comment by turshija** [comment]
I Andrej zvuci cudno u Vokativu ...

**Comment by turshija** [comment]
Zensko ime Mia - http://gorila.jutarnji.hr/profile/knjiga/2011/02/02/deklinacija-imena-mia

**Comment by Shonetow** [comment]
Mia je sređena, a za Aleksandra i Andreja ću se pobrinuti sutra. Hvala. :)

**Comment by Shonetow** [comment]
Mia ipak ne dobija "j" po srpskom pravopisu, a po hrvatskom valjda da. Aleksandar i Andrej su sređeni, kao i (X)orivoj i sl.

Zatvoriću ovaj issue, pa za svako drugo ime neka se otvori novi, čisto zbog neke evidencije i preglednosti.
